version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quarkusdb
      MYSQL_USER: quarkus
      MYSQL_PASSWORD: quarkus
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
